title: Chandler Severson's Portfolio
email: me@cseverson.com
description: >- # this means to ignore newlines until "baseurl:"
  Write-ups for some of my most interesting software projects.
baseurl: ""
url: "https://chandl.io" # the base hostname & protocol for your site, e.g. http://example.com
author: Chandler Severson
show_excerpts: true # set to true to show excerpts on the homepage
resume_url: "https://drive.google.com/file/d/1R4TYUs-TFfwRkajIDn85tiloUQQDyH50/view?usp=sharing"
collections:
  - experience
  - education
  - projects

social_links:
  linkedin: "https://www.linkedin.com/in/chandler-severson/"
  github: "https://github.com/chandl"
  stackoverflow: "https://stackoverflow.com/users/6321578/chandler"