title: Chandler Severson Tech
email: me@cseverson.com
description: >- # this means to ignore newlines until "baseurl:"
  Write-ups for some of my most interesting software projects.
baseurl: "/blog"
url: "https://www.cseverson.com" # the base hostname & protocol for your site, e.g. http://example.com
theme: minima
author: Chandler Severson
show_excerpts: true # set to true to show excerpts on the homepage